options:
    resources_mirror:
        type: string
        default: ''
        description: |
            URL used to fetch resources (e.g., Hadoop binaries) instead of the
            location specified in resources.yaml.
    spark_execution_mode:
        type: string
        default: 'yarn-client'
        description: |
            Options are "local" for standalone (no YARN), "yarn-client", and
            "yarn-cluster"
